ARG BASE_VER=latest
FROM mbentley/omada-controller:${BASE_VER}

RUN apt-get update &&\
  apt-get install -y --no-install-recommends software-properties-common &&\
  add-apt-repository ppa:saiarcot895/chromium-beta &&\
  apt-get update &&\
  DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends chromium-browser &&\
  apt-get purge -y software-properties-common &&\
  apt-get autoremove -y &&\
  rm -rf /var/lib/apt/lists/*
