# rebased/repackaged base image that only updates existing packages
FROM mbentley/ubuntu:20.04
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"
LABEL org.opencontainers.image.source="https://github.com/mbentley/docker-omada-controller"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
  apt-get install --no-install-recommends -y ca-certificates jq libcurl4 wget &&\
  rm -rf /var/lib/apt/lists/*

RUN cd /tmp &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.0.28.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.2.23.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.4.18.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-5.0.31.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.25.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-7.0.22.tgz &&\
  wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-8.0.12.tgz &&\
  wget -q https://downloads.mongodb.com/compass/mongosh-2.3.9-linux-x64.tgz &&\
  tar xvf mongodb-linux-x86_64-ubuntu1804-4.0.28.tgz mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongod mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongo &&\
  tar xvf mongodb-linux-x86_64-ubuntu1804-4.2.23.tgz mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongod mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongo &&\
  tar xvf mongodb-linux-x86_64-ubuntu1804-4.4.18.tgz mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongod mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongo &&\
  tar xvf mongodb-linux-x86_64-ubuntu2004-5.0.31.tgz mongodb-linux-x86_64-ubuntu2004-5.0.31/bin/mongod mongodb-linux-x86_64-ubuntu2004-5.0.31/bin/mongo &&\
  tar xvf mongodb-linux-x86_64-ubuntu2004-6.0.25.tgz mongodb-linux-x86_64-ubuntu2004-6.0.25/bin/mongod &&\
  tar xvf mongodb-linux-x86_64-ubuntu2004-7.0.22.tgz mongodb-linux-x86_64-ubuntu2004-7.0.22/bin/mongod &&\
  tar xvf mongodb-linux-x86_64-ubuntu2004-8.0.12.tgz mongodb-linux-x86_64-ubuntu2004-8.0.12/bin/mongod &&\
  tar xvf mongosh-2.3.9-linux-x64.tgz mongosh-2.3.9-linux-x64/bin/mongosh &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongod mongod-4.0.28 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongod mongod-4.2.23 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongod mongod-4.4.18 &&\
  mv mongodb-linux-x86_64-ubuntu2004-5.0.31/bin/mongod mongod-5.0.31 &&\
  mv mongodb-linux-x86_64-ubuntu2004-6.0.25/bin/mongod mongod-6.0.25 &&\
  mv mongodb-linux-x86_64-ubuntu2004-7.0.22/bin/mongod mongod-7.0.22 &&\
  mv mongodb-linux-x86_64-ubuntu2004-8.0.12/bin/mongod mongod-8.0.12 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.0.28/bin/mongo mongo-4.0.28 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.2.23/bin/mongo mongo-4.2.23 &&\
  mv mongodb-linux-x86_64-ubuntu1804-4.4.18/bin/mongo mongo-4.4.18 &&\
  mv mongodb-linux-x86_64-ubuntu2004-5.0.31/bin/mongo mongo-5.0.31 &&\
  mv mongosh-2.3.9-linux-x64/bin/mongosh mongosh &&\
  rm -rf mongodb-* mongosh-*

COPY upgrade.sh /

ENV DEBUG=false

WORKDIR /opt/tplink/EAPController/lib
ENTRYPOINT ["/upgrade.sh"]
