# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:latest
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# build deps
RUN apk --no-cache add gcc musl-dev

# add in source
COPY atomic.c /A

# compile
RUN gcc -g atomic.c -o atomic -march=armv8.2-a -lpthread -static
